version: '3.8'

networks:
  # Required for the devcontainer
  sindit_network:
    name: sindit_network

services:
  sindit_influx_db:
    extends:
      file: docker-compose.databases.yml
      service: sindit_influx_db
    networks:
      - sindit_network
    ports:
      - '8086:8086'

  sindit_neo4j_kg:
    extends:
      file: docker-compose.databases.yml
      service: sindit_neo4j_kg
    networks:
      - sindit_network
    ports:
      - 7474:7474
      - 7687:7687

  sindit_minio_s3:
    extends:
      file: docker-compose.databases.yml
      service: sindit_minio_s3
    networks:
      - sindit_network
    ports:
      - "9000:9000"
      - "9099:9099"

  zookeeper:
    image: 'zookeeper:3.7'
    networks:
      - sindit_network
    ports:
      - '2181:2181'

  kafka:
    image: 'confluentinc/cp-kafka:latest'
    depends_on:
      - zookeeper
    networks:
      - sindit_network
    ports:
      - '9092:9092'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mqtt_kafka_bridge:
    image: mqtt-kafka-bridge
    depends_on:
      - kafka
    networks:
      - sindit_network


volumes:
  sindit-minio-s3-volume:
  sindit-neo4j-conf-volume:
  sindit-neo4j-logs-volume:
  sindit-neo4j-data-volume:
  sindit-influx-db-data-volume:
  sindit-influx-db-config-volume:
  sindit-kafka-data-volume:
